export const EMPLOYER_CATEGORIES = {
  "A+": [
    "TCS", "Infosys", "HCLTech", "Wipro", "Accenture",
    "IBM India", "Microsoft India", "Google India", "Amazon India",
    "Apple India", "Deloitte", "EY", "KPMG", "PwC",
    "Reliance Industries", "Tata Consultancy Services", "Tata Motors",
    "Tata Steel", "Tata Consumer Products", "Titan Company", "Tata Power",
    "Tata Communications", "Tata Electronics", "Tata Capital", "Tata AIG",
    "Tata Advanced Systems", "Tata Technologies", "Larsen & Toubro",
    "LTIMindtree", "L&T Technology Services", "Reliance Jio", "Reliance Retail",
    "Aditya Birla Group", "Hindalco Industries", "UltraTech Cement",
    "Grasim Industries", "Aditya Birla Capital", "Aditya Birla Fashion",
    "Vodafone Idea", "Mahindra & Mahindra", "Tech Mahindra", "Mahindra Finance",
    "Mahindra Logistics", "Mahindra Lifespaces", "ONGC", "Indian Oil Corporation",
    "Bharat Petroleum", "Hindustan Petroleum", "GAIL", "Coal India", "NTPC",
    "Power Grid Corporation of India", "BHEL", "SAIL", "HAL", "BEL", "BEML",
    "NMDC", "NLC India", "Oil India", "Engineers India", "Power Finance Corporation",
    "REC", "Indian Railway", "State Bank of India", "Bank of Baroda",
    "Punjab National Bank", "Canara Bank", "Union Bank of India", "Bank of India",
    "Indian Bank", "Central Bank of India", "Indian Overseas Bank",
    "Bank of Maharashtra", "UCO Bank", "Punjab & Sind Bank", "LIC", "NABARD",
    "EXIM Bank", "SIDBI", "Central/State Government", "Defence", "Railways",
    "Major PSBs", "Large PSU companies",
    "Indian Army", "Indian Navy", "Indian Air Force", "DRDO", "ISRO", "RBI"
  ],
  "A": [
    "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra Bank", "IndusInd Bank",
    "IDFC First Bank", "Yes Bank", "Federal Bank", "RBL Bank", "Bandhan Bank",
    "South Indian Bank", "City Union Bank", "Karur Vysya Bank", "Karnataka Bank",
    "DCB Bank", "CSB Bank", "Tamilnad Mercantile Bank", "Jammu & Kashmir Bank",
    "AU Small Finance Bank", "Ujjivan Small Finance Bank", "Equitas Small Finance Bank",
    "Jana Small Finance Bank", "ESAF Small Finance Bank", "Suryoday Small Finance Bank",
    "Utkarsh Small Finance Bank", "Bajaj Finance", "Bajaj Finserv", "Shriram Finance",
    "Cholamandalam Investment & Finance", "Muthoot Finance", "Manappuram Finance",
    "L&T Finance", "Sundaram Finance", "Poonawalla Fincorp", "LIC Housing Finance",
    "Can Fin Homes", "PFC", "IIFL Finance", "Five-Star Business Finance",
    "Aptus Value Housing Finance", "Aavas Financiers", "Home First Finance",
    "CreditAccess Grameen", "Ugro Capital", "Aditya Birla Finance", "HDB Financial Services", "Muthoot Fincorp", "Mphasis", "Coforge", "Persistent Systems",
    "Hexaware Technologies", "KPIT Technologies", "Mastek", "Cyient", "Birlasoft",
    "Sonata Software", "Zensar Technologies", "Happiest Minds", "Newgen Software",
    "Oracle India", "SAP India", "Cisco India", "Adobe India", "Salesforce India",
    "Dell Technologies India", "Hewlett Packard Enterprise India", "Capgemini India",
    "Cognizant India", "Genpact", "WNS", "EXL", "Concentrix", "Teleperformance India",
    "Maruti Suzuki", "Hyundai Motor India", "Toyota Kirloskar Motor", "Honda Cars India",
    "Honda Motorcycle & Scooter India", "Hero MotoCorp", "Bajaj Auto", "TVS Motor",
    "Eicher Motors", "Ashok Leyland", "Force Motors", "Renault India", "Kia India",
    "MG Motor India", "Isuzu Motors India", "Volkswagen India", "Skoda Auto India",
    "Daimler India Commercial Vehicles", "Volvo Eicher Commercial Vehicles",
    "Sun Pharma", "Dr. Reddy's Laboratories", "Cipla", "Lupin", "Aurobindo Pharma",
    "Zydus Lifesciences", "Torrent Pharmaceuticals", "Alkem Laboratories", "Biocon",
    "Glenmark Pharmaceuticals", "Divi's Laboratories", "Abbott India", "Mankind Pharma",
    "Alembic Pharmaceuticals", "Ipca Laboratories", "Laurus Labs", "Natco Pharma",
    "Granules India", "Ajanta Pharma", "Piramal Pharma", "Hindustan Unilever", "ITC",
    "Nestlé India", "Britannia Industries", "Dabur India", "Marico",
    "Godrej Consumer Products", "Colgate-Palmolive India", "Procter & Gamble India",
    "Reckitt India", "Emami", "Patanjali Foods", "Varun Beverages", "United Breweries",
    "United Spirits", "Asian Paints", "Berger Paints", "Kansai Nerolac",
    "Pidilite Industries", "Bharti Airtel", "Tata Teleservices", "RailTel",
    "Indus Towers", "Adani Enterprises", "Adani Ports", "Adani Power",
    "Adani Energy Solutions", "Adani Green Energy", "Adani Total Gas",
    "Shapoorji Pallonji", "NCC", "KNR Constructions", "Dilip Buildcon",
    "Ashoka Buildcon", "IRB Infrastructure", "GMR Airports", "G R Infraprojects",
    "Kalpataru Projects", "KEC International", "RVNL", "IRCON", "NBCC", "JSW Steel",
    "JSW Energy", "Hindalco", "Vedanta", "Jindal Steel & Power", "Jindal Stainless",
    "Hindustan Zinc", "MOIL", "NALCO", "National Mineral Development Corporation",
    "Rashtriya Ispat Nigam",
    
    // Additional Navratna CPSEs
    "Bharat Electronics Limited (BEL)", "Container Corporation of India Limited (CONCOR)", 
    "Engineers India Limited (EIL)", "Mahanagar Telephone Nigam Limited (MTNL)", 
    "National Aluminium Company Limited (NALCO)", "National Buildings Construction Corporation Limited (NBCC)", 
    "Neyveli Lignite Corporation Limited (NLC)", "NMDC Limited", "Rashtriya Ispat Nigam Limited (RINL)", 
    "Shipping Corporation of India Limited (SCI)", "Rail Vikas Nigam Limited (RVNL)", 
    "ONGC Videsh Ltd (OVL)", "Rashtriya Chemicals & Fertilizers Limited (RCFL)", 
    "IRCON International", "RITES Limited", "National Fertilizers Limited (NFL)", 
    "Central Warehousing Corporation (CWC)", "Housing & Urban Development Corporation Limited (HUDCO)", 
    "Indian Renewable Energy Development Agency Limited (IREDA)", "Mazagon Dock Shipbuilders Limited (MDL)", 
    "Railtel Corporation of India Limited", "Solar Energy Corporation of India (SECI) Ltd.", 
    "NHPC Limited", "SJVN Limited",

    // Additional Miniratna Category I & II
    "Airports Authority of India (AAI)", "Antrix Corporation Limited", "Balmer Lawrie & Co. Limited", 
    "Bharat Coking Coal Limited (BCCL)", "Bharat Dynamics Limited (BDL)", "BEML Limited", 
    "Bharat Sanchar Nigam Limited (BSNL)", "Braithwaite & Company Limited", "Bridge & Roof Company (India) Limited", 
    "Central Coalfields Limited (CCL)", "Central Electronics Limited (CEL)", "Central Mine Planning & Design Institute Limited (CMPDI)", 
    "Chennai Petroleum Corporation Limited (CPCL)", "Cochin Shipyard Limited", "Cotton Corporation of India Ltd", 
    "EDCIL (India) Limited", "Garden Reach Shipbuilders & Engineers Limited (GRSE)", "Grid Controller of India Limited (GRID-INDIA)", 
    "Goa Shipyard Limited", "Hindustan Copper Limited (HCL)", "Hindustan Steelworks Construction Limited", 
    "HLL Lifecare Limited", "Hindustan Newsprint Limited", "Hindustan Paper Corporation Limited", 
    "HSCC (India) Limited", "India Tourism Development Corporation Limited (ITDC)", "Indian Rare Earths Limited (IREL)", 
    "India Trade Promotion Organization (ITPO)", "KIOCL Limited", "Mahanadi Coalfields Limited (MCL)", 
    "MOIL Limited", "Mangalore Refinery & Petrochemical Limited (MRPL)", "Mineral Exploration Corporation Limited (MECL)", 
    "Mishra Dhatu Nigam Limited (MIDHANI)", "MMTC Limited", "MSTC Limited", "National Projects Construction Corporation Limited (NPCC)", 
    "National Small Industries Corporation Limited (NSIC)", "National Seeds Corporation (NSC)", "Northern Coalfields Limited (NCL)", 
    "North Eastern Electric Power Corporation Limited (NEEPCO)", "Numaligarh Refinery Limited (NRL)", "Pawan Hans Helicopters Limited", 
    "Projects & Development India Limited (PDIL)", "Security Printing and Minting Corporation of India Limited (SPMCIL)", 
    "South Eastern Coalfields Limited (SECL)", "Telecommunications Consultants India Limited (TCIL)", "THDC India Limited", 
    "Western Coalfields Limited", "Artificial Limbs Manufacturing Corporation of India (ALIMCO)", 
    "Bharat Pumps & Compressors Limited", "Broadcast Engineering Consultants India Limited (BECIL)", 
    "Central Railside Warehouse Company Limited", "Engineering Projects (India) Limited (EPIL)", 
    "FCI Aravali Gypsum & Minerals India Limited", "Ferro Scrap Nigam Limited (FSNL)", "HMT (International) Limited", 
    "Indian Medicines & Pharmaceuticals Corporation Limited (IMPCL)", "MECON Limited", "National Film Development Corporation Limited (NFDC)", 
    "Rajasthan Electronics & Instruments Limited (REIL)",

    // Defence, Aerospace, and Railway Subsidiaries
    "Advanced Weapons and Equipment India Limited (AWEIL)", "Armoured Vehicles Nigam Limited (AVNL)", 
    "Defence Offsets Management Wing (DOMW)", "Gliders India Limited (GIL)", "Gun and Shell Factory Cossipore", 
    "Troop Comforts Limited (TCL)", "Yantra India Limited (YIL)", "Munitions India Limited (MIL)", 
    "India Optel Limited (IOL)", "Hindustan Shipyard Limited (HSL)", "Solar Industries India Limited", 
    "Tata Advanced Systems Limited (TASL)", "Bharat Forge Limited", "Data Patterns India", "Zen Technologies",
    "Dedicated Freight Corridor Corporation of India Limited (DFCCIL)", "Indian Railway Catering and Tourism Corporation (IRCTC)", 
    "Konkan Railway Corporation (KRC)", "Indian Railway Finance Corporation (IRFC)", "Mumbai Rail Vikas Corporation (MRVC)", 
    "Centre for Railway Information Systems (CRIS)", "Rail Land Development Authority (RLDA)",
    "Central Inland Water Transport Corporation Limited", "Certification Engineers International Limited", 
    "Delhi Police Housing Corporation", "Hindustan Antibiotics Limited", "HIL (India) Limited", 
    "Hindustan Photo Films Manufacturing Company Limited", "Hindustan Prefab Limited", "Hindustan Salts Limited", 
    "HMT Bearings Limited", "HMT Chinar Watches Limited", "Hooghly Dock and Port Engineers Limited", 
    "Birds Jute & Exports Limited", "Hindustan Fluorocarbons Limited", "Orissa Drugs & Chemicals Limited", 
    "Rajasthan Drugs & Pharmaceuticals Limited", "Bel Optronics Ltd", "Electronics Corporation of India Limited", 
    "Fertilizers & Chemicals (Travancore) Limited (FACT)", "Food Corporation of India (FCI)", "NewSpace India Limited", 
    "National Textiles Corporation Limited", "Power System Operation Corporation Limited", "Andrew Yule & Company Limited", 
    "Air India Assets Holding Company Limited", "Bharat Gas Resources Limited", "Bharat Petro Resources Limited", 
    "Cement Corporation of India Limited", "Brithwaite Burn & Jessop Construction Company Limited", 
    "Bengal Chemicals & Pharmaceuticals Limited", "BHEL Electric Machines Limited", "Bharat Wagon & Engineering Company Limited", 
    "The Bisra Stone Lime Company Limited", "Central Cottage Industries Corporation of India Limited",

    // Major IT & Consulting Services / Global BPOs / Specialized KPOs
    "AppInventiv", "CONTUS Tech", "Grant Thornton", "Larsen & Toubro Infotech (LTI)", "PKF International", 
    "Virtusa", "Mobisoft Infotech", "Cigniti Technologies", "WHMCS Global Services", "Sagar Informatics Pvt. Ltd.", 
    "Cyber Infrastructure (CIS)", "Dotsquares", "Synoptek", "MTOAG Technologies", "TatvaSoft", "Tvisha Technologies", 
    "Fingent", "i2k2 Networks", "Algoworks", "Mutual Mobile", "Expertrec", "Radixweb", "Carmatec", "Pro Web", 
    "Xicom", "XenonStack", "Affirma", "The NineHertz", "TechAhead", "OnGraph", "Concetto Labs", "Quytech", 
    "Aufait Technologies", "Quest", "SunTec India", "TCS BPO", "Infosys BPM", "Wipro BPO", "HCL Technologies BPO", 
    "IBM Global Process Services", "Tech Mahindra BPO", "Conduent", "Firstsource Solutions", "WNS Global Services", 
    "EXL Service", "Sutherland Global Services", "Capgemini Business Services (CBS)", "NTT DATA Business Solutions", 
    "Hinduja Global Solutions (HGS)", "Serco Global Services", "Wipro Spectramind", "Aditya Birla Minacs", 
    "Aegis (Teleperformance)", "Hinduja Tech", "WNS DecisionPoint", "TaskUs", "Startek", "iEnergizer", "Sagility",
    "Evalueserve", "CRISIL", "ICRA Limited", "Moody's Analytics Knowledge Services (Copal Amba)", "Access Healthcare", 
    "Pangea3", "QuisLex", "Ugam Solutions", "The Smart Cube", "Irevna"
  ],
  "B": [
    // Regional Industrial & Manufacturing (Agra/UP/National)
    "Hari industries", "B. KAMAL INDUSTRIES", "Mahavir Industries", "Sharda Oil Industries Pvt. Ltd.", 
    "Pankaj Industries", "Paragon Industries", "S.s. Industries", "Amar Oil Industries", "Bankey Bihari Glass Industries", 
    "Bansal Industries & Tickly Cutting Udhyog", "BRONZERR INDUSTRIES PVT. LTD.", "C. P. AGRO INDUSTRIES PVT. LTD.", 
    "Chaudhary Industries", "Chavi Stone Industry", "Gitansh Industries", "HEIGHT POLES INDUSTRIES", "J B OIL INDUSTRIES", 
    "Jai Bholey Baba Industries", "JAI MAAI NIWAR INDUSTRIES", "Krsnaye Industrial Private Limited", "M.B. Industries", 
    "M.R Oil Industries (Eagle Brand Mustard Oil)", "M/S Radha Govind Niwar Industries", "Moon Line Industry", "Nandi Industry", 
    "R.C. INDUSTRIES", "Roger Industries", "Sandeep Rubber (I) Industries", "Shakun Scientific Industries", "Shri Gokulesh Exports", 
    "Atul Group Of Industries", "Jai Pushpa Industries", "Jain Industries", "Luthra Industrial Corporation", "Supreme Plast Industries",
    "Sks Infra Projects Pvt Ltd", "Agra Tundla Transport", "Dtdc Courier", "Jai Chandra Distributors", "Gupta Overseas", "Dawar InfraBuild",
    "Amul", "Aavin",

    // Mid-Cap Process Outsourcing & Regional IT
    "The Octopus Tech", "Intellize Info Solutions", "TechSpeed Inc", "Uniquesdata", "Ask Datatech", "GOIGI.com", 
    "IBN Technologies LLC", "KG Invicta Services", "CapActix Business Solutions", "Viaante Business Solutions", 
    "Eminenture", "Virtual Eases", "Atellier Studio", "Data Entry Export", "Eternity Paralegal Services", 
    "YourDailyTask", "ClousTech Solutions", "Technosys IT Management Private Limited", "Covrize It Solutions", 
    "FSL", "eClerx", "RPSG Ventures", "OnePoint", "AllDigi", "NSB BPO", "Kandarp", "Cadsys", "WeWin", "HRH Next", 
    "Infortec", "POBS", "BNR Udyog", "Plada Info", "GTE IT"
  ],
  "C": [
    // Local Tech, Digital & Media Services
    "Infira Technologies private limited", "ArahaSoft Private Limited", "Adpilot Media", "Auctor Media Pvt Ltd", 
    "Vellumarc Digital", "Techart India Private Limited", "YourStory", "Smartkeeda", "DevDiggers",
    
    // Regional Services, Consultancies & Retail
    "choudhary motors", "SPH GROUP", "Lucknow Cab Service", "Noida Travellers", "Stalwart Career Institute Agra", 
    "A M G Events INDIA", "Akshat Financial Consultants", "Guide Finder", "Kkgi Group", "Bada Business Agra", 
    "Civic Services", "Rajendra Centre", "Rajendra Space", "Collab Workspaces Llp", "A.f.d. Estate", 
    "Mulberry Tree Office", "Vim Security Services", "Bhagat Halwai Pvt Ltd", "Kalakrit Cultural & Convention Centre", 
    "Mughal Fire Works", "LIC Of India (Customer Care / Agencies)", "Torrent Power Jaipur House / Office", 
    "PNB Metlife Insurance Co Ltd", "New Tundla Station EDFC", "Bhartiya Janta Party Office", "Tehsil Court", 
    "U P Awas Evam Vikas Parishad",

    // Emerging Startup Recruiting Channels & Micro-Finance
    "Almas Exports and Imports Private Limited", "Hindustan Unilever (Sumerpur plant - specific trainee roles)", 
    "SBI Life Insurance (advisor roles)", "TGBPL TP India", "Varthana Finance Pvt Ltd"
  ],
  "Other": [
    "Other / My company isn't listed"
  ]
};

// Flattened list for the search dropdown
// Automatically remove duplicates just in case
export const EMPLOYERS = Array.from(new Set([
  ...EMPLOYER_CATEGORIES["A+"],
  ...EMPLOYER_CATEGORIES["A"],
  ...EMPLOYER_CATEGORIES["B"],
  ...EMPLOYER_CATEGORIES["C"],
  ...EMPLOYER_CATEGORIES["Other"]
]));
